accupara/docker-images

chromium/Dockerfile

1. One RUN command instead of 3
2. One package per line sorted alphabetically
3. Cleanup at the end

Formatting the Dockerfile for chromium.

---

Makefile
k8s/Dockerfile
k8s/Makefile
k8s/sshd_config

Pretty simple: Take the publicly available k8s cross build image and add the parts requried for Crave to work properly

Build container for k8s cross compilation

---

baseimages/alpine/3.9/Dockerfile
baseimages/alpine/3.9/Makefile
baseimages/alpine/3.9/sshd_config
timescaledb/alpine/3.9/Dockerfile
timescaledb/alpine/3.9/Makefile
timescaledb/ubuntu/18.04/Dockerfile
timescaledb/ubuntu/18.04/Makefile

Add alpine containers and add build container for timescaledb based on
alpine and ubuntu.

Add alpine and timescaledb

---

cmake-examples/Dockerfile
cmake-examples/Makefile

Add a new docker file to build the project: https://github.com/ttroy50/cmake-examples

Added docker file for cmake-examples project

---

docker-builder/Dockerfile
docker-builder/Makefile

what the title says. We can use this container and setup a project for github.com/accupara/docker-images

Add container to build docker images

---

protocolbuffers/Dockerfile
protocolbuffers/Makefile

Add container to build grpc and protocol buffers

---

linuxkernel/amd64/Dockerfile

linux kernel build deps updated

linux kernel dockerfile: add cpio

---

fluentd/Dockerfile
fluentd/Makefile

Added fluentd image with elasticsearch plugin

Added fluentd image with elasticsearch plugin

---

baseimages/aosp/Dockerfile

add brotli, libfreetype6 and openjdk-11

add packages required for LineageOS build

---

crave/devspace/Dockerfile
crave/devspace/Makefile

- create a devspace specific container with grpcurl built in based
on ubuntu 20.04

Devspace container with grpcurl

---

windows/chocobase-ltsc2019/Dockerfile
windows/chocobase-ltsc2019/Makefile
windows/chocobase-ltsc2019/install.ps1

with all the required tools for crave base image

Added chocobase-ltsc2019

---

linuxkernel/Dockerfile

Add gawk and qemu-kvm for rcutorcher

Lkbuild gawk qemu

---

ubuntu-k8s/Dockerfile
ubuntu-k8s/LICENSE
ubuntu-k8s/Makefile
ubuntu-k8s/README.md
ubuntu-k8s/logger.sh
ubuntu-k8s/modprobe
ubuntu-k8s/startup.sh
ubuntu-k8s/supervisor/dockerd.conf

Ubuntu-k8s image added

---

ubuntu-k8s/Dockerfile.dcuser.default
ubuntu-k8s/startup.sh

To build use
```
export DOCKERFILE=Dockerfile.dcuser.default
export IMGTAG=ubuntu-k8s-docker
make build
```
To push, peform `docker login` first

new docker image with dcuser as default

---

db/postgres/rockylinux/8/Dockerfile
db/postgres/rockylinux/8/Makefile
db/postgres/rockylinux/9/Dockerfile
db/postgres/rockylinux/9/Makefile
db/postgres/rockylinux/Makefile

We are working on building orioledb rpms with crave, during a meeting with Yuvraj, we decided to issue this PR.

Adding postgres images for rockylinux

---

Makefile
arch-aosp-jdk7/Dockerfile
arch-aosp-jdk7/Makefile
arch-aosp-jdk7/resync.sh
arch-aosp-jdk8/Dockerfile
arch-aosp-jdk8/Makefile
arch-aosp-jdk8/resync.sh
baseimages/phase1/arch/Dockerfile
baseimages/phase1/arch/Makefile
baseimages/phase1/arch/sshd_config

Arch images with jdk 8, jdk 7 and python2

Add more AOSP Images

---

aosp/common/upload.sh

upload.sh: Find Image files instead of using wildcard

---

aosp/common/upload.sh
crave/devspace/Dockerfile

still needs token.txt with PAT from user's end

upload.sh: Support for devspace

---

aosp/ubuntu/Dockerfile
baseimages/phase1/arch/Dockerfile

iputils, inetutils, xmlstarlet on 
Thanks to Riveeks Smooth for the list

Arch and AOSP Ubuntu: Fetch packages

---

aosp/common/tgup.sh
aosp/common/upload.sh

Allow user to set upload limits for github releases and telegram-upload(in case they have higher tiers)

Check Upload limit variables

---

aosp/common/tgup.sh
aosp/common/upload.sh

*Fix black upload issue
*Add support for extra files

Upload: Various fixes

---

aosp/ubuntu/Dockerfile

it's looks necessary to build mesa3d in aosp

aosp: ubuntu: Add meson, ninja and pkg-config

---

crave/devspace/Dockerfile

Using this as a guide:
https://github.com/nodesource/distributions/blob/master/README.md#using-ubuntu-1

devspace: Set NodeJS version to 20

---

aosp/arch/jdk7/Dockerfile
aosp/arch/jdk8/Dockerfile
aosp/arch/python2/Dockerfile
baseimages/phase1/arch/Dockerfile

-> use archlinux/archlinux:multilib-devel as base image's base image | official image with multilib-devel meta pkg installed 
-> install paru in base image | it's needed in all other (3) dependent images 
-> clear cache files at last

archlinux: misc. improvements

---

aosp/baseline/Dockerfile

https://gitlab.com/androidsantoni/device/device_xiaomi_santoni/-/commit/e72d0fe5c47a7e81dd97b66ebeb606d75b23f781

make `/etc/mke2fs.conf` writable

---

crave/ollama-with-ui/Dockerfile
crave/ollama-with-ui/Makefile

- add packages to the ollama docker image to support gpus and training

---

baseimages/phase1/arch/Dockerfile

needed package to view git diffs

add `less` package

---

mozilla/firefox/desktop/Dockerfile

* Update link to the new official repository
* Add application choice flag in bootstrap command

Update Mozilla firefox dockerfile
